variables:
    SSH_USER: SSH_USER
    SSH_PRIVATE: SSH_PRIVATE
    HOST: HOST
    PATH: PATH

build:
  stage: build
  image: python:3.13
  script:
    - pip install -r .acimov/requirements.txt
    - python .acimov/publish.py
  artifacts:
    paths:
      - public
  only:
    - master


deploy:
  stage: deploy
  image: maximelefrancois86/alpine-ssh-rsync
  script:
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SSH_PRIVATE")
    - mkdir -p ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - rsync -rtcv public/ $USER@$HOST:$PATH
  only:
    - master
