name: deploy
on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: actions/setup-python@v4
      with:
        python-version: '3.x'
        cache: 'pip'
    - run: pip install -r .acimov/requirements.txt
    - run: python .acimov/publish.py
    - name: rsync deployments
      uses: burnett01/rsync-deployments@7.0.2
      with:
        switches: -a
        path: public/
        remote_path: /var/www/aec3po/html
        remote_host: ci.mines-stetienne.fr
        remote_user: aec3po
        remote_key: ${{ secrets.SSH_PRIVATE }}
