name: test
on:
  push:
    branches:
    - '**' # matches every branch
    - '!main'   # excludes main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: actions/setup-python@v4
      with:
        python-version: '3.x'
        cache: 'pip'
    - run: pip install -r .acimov/requirements.txt
    - run: python .acimov/publish.py
    - uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
        publish_branch: documentation