name: test
on:
  push:
    branches:
    - '**' # matches every branch
    - '!master'   # excludes master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'
        cache: 'pip'
    - run: pip install -r .acimov/requirements.txt
    - run: python .acimov/publish.py
